# permissions for end users to edit base64controllers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-base64-encode-controller
    app.kubernetes.io/managed-by: kustomize
  name: base64controller-editor-role
rules:
- apiGroups:
  - kubernetes-base64-encode-controller.my.domain
  resources:
  - base64controllers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes-base64-encode-controller.my.domain
  resources:
  - base64controllers/status
  verbs:
  - get
