---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubernetes-base64-encode-controller.my.domain
  resources:
  - base64controllers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes-base64-encode-controller.my.domain
  resources:
  - base64controllers/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetes-base64-encode-controller.my.domain
  resources:
  - base64controllers/status
  verbs:
  - get
  - patch
  - update
